version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - ng update
      - npm update
  build:
    commands:
      - echo Entered the build phase... 

      - ng build
  post_build:
    commands:
      - echo Copy files to the destination bucket
      - aws s3 sync --acl public-read --delete ./dist/empatica-webapp s3://$WEBAPP_BUCKET 